/**
 * Motivational quotes for spending confirmations
 * Format: quotes contain {name} placeholder that will be replaced with user's name
 */

export const MOTIVATIONAL_QUOTES = [
  "Nice move, {name}. Every penny has a purpose.",
  "Great tracking, {name}—clarity today, freedom tomorrow.",
  "Well done, {name}. Consistency compounds.",
  "Another clean log, {name}. Momentum loves this.",
  "Strong choice, {name}—future you says thanks.",
  "Every entry is a deposit into discipline, {name}.",
  "Budget updated, {name}; stress downgraded.",
  "You just voted for your goals with your wallet, {name}.",
  "Tiny action, big trajectory, {name}.",
  "Your plan > your impulses, {name}. Keep going.",
  "Recorded and remembered, {name}—money obeys math.",
  "Precision today, peace later, {name}.",
  "Progress over perfection, {name}. Keep stacking.",
  "Stacking wins like coins, {name}.",
  "Tracking is training, {name}. You're getting stronger.",
  "Legendary consistency, {name}—keep cashing it in.",
  "Another brick in your freedom wall, {name}.",
  "Smarter chapter added to your money story, {name}.",
  "Logs like this turn dreams into line items, {name}.",
  "That click is the sound of control, {name}.",
  "You guided money; it didn't guide you, {name}.",
  "Discipline looks good on you, {name}.",
  "Habits like this build safety nets, {name}.",
  "Order made, chaos avoided—well played, {name}.",
  "Budget boundaries protect your joy, {name}.",
  "Microwin achieved, {name}. Macro gains incoming.",
  "Accuracy today makes choices easy tomorrow, {name}.",
  "Future you is high-fiving you, {name}.",
  "Wealth sneaks up on habits like yours, {name}.",
  "You paid your goals first—with attention, {name}.",
  "Calm cash beats loud purchases, {name}.",
  "Streak protected, {name}. Nice work.",
  "Notebook brain, investor heart, {name}—love it.",
  "From wishful to mindful in one tap, {name}.",
  "The trend line smiled at you, {name}.",
  "Entry locked, temptations blocked, {name}.",
  "Slow is smooth, smooth is rich, {name}.",
  "Values over vibes—chef's kiss, {name}.",
  "Boss move: budget first, then life, {name}.",
  "Receipts of progress filed, {name}.",
  "You're training your money to behave, {name}.",
  "Control earned, {name}. Feels good, right?",
  "Your goals are in range, {name}. Signals clear.",
  "That was a vote for financial freedom, {name}.",
  "Numbers noted, nervousness muted, {name}.",
  "You're building options, not just savings, {name}.",
  "Money clarity activated, {name}.",
  "Another notch on your wealth belt, {name}.",
  "Quiet win, loud future, {name}.",
  "Tiny hinges swing big doors, {name}.",
  "Compound returns love consistent trackers like you, {name}.",
  "Every line item is leadership, {name}.",
  "Budget armor upgraded, {name}.",
  "Cents into sense—nice work, {name}.",
  "Road to rich is paved with logs like this, {name}.",
  "You're buying time, not things, {name}.",
  "Minutes of tracking; years of payoff, {name}.",
  "From chaos to cadence—clean entry, {name}.",
  "{name}, you're the CFO of your life.",
  "Budget beast mode engaged, {name}.",
  "Debt hated what you just did, {name}.",
  "Savings smiled; impulse pouted, {name}.",
  "You made temptation wait its turn, {name}.",
  "Habit over hype—great form, {name}.",
  "Aligned spend, aligned life, {name}.",
  "Good call—needs over noise, {name}.",
  "You kept tomorrow's promise, {name}.",
  "The plan got sharper, and so did you, {name}.",
  "Beginner mode now; pro soon, {name}.",
  "Clean entry, clear conscience, {name}.",
  "Your goals just got closer, {name}.",
  "Strong log, less fog, {name}.",
  "Your baseline is rising, {name}. Keep going.",
  "Make money boring; make life exciting, {name}.",
  "Order in the budget, peace in the mind, {name}.",
  "Your priorities are showing—in a good way, {name}.",
  "Money knows who's boss: you, {name}.",
  "Win logged; confidence credited, {name}.",
  "You protected your peace and your purse, {name}.",
  "Calm, clear, consistent—wealth loves that, {name}.",
  "Receipts don't lie; streaks don't either, {name}.",
  "Budget updated; motivation upgraded, {name}.",
  "Steady hands, steady plans, {name}.",
  "Wealth is a habit—keep repping, {name}.",
  "Progress over impulse—textbook, {name}.",
  "Tracking today keeps regret away, {name}.",
  "Future decisions just got easier, {name}.",
  "That entry punched debt in the face, {name}.",
  "Savings meter ticked up, {name}.",
  "Mastering money, not chasing it—nice, {name}.",
  "Another disciplined dollar, {name}.",
  "Goals fed; impulse unfed, {name}.",
  "Your path is visible, {name}. Crystal clear.",
  "You keep your budget promises, {name}.",
  "Long game pro move, {name}.",
  "Guardrails held—well done, {name}.",
  "Financial muscles engaged, {name}.",
  "Clarity is compounding, {name}.",
  "You banked a little more freedom, {name}.",
  "Logs like this build legacies, {name}.",
  "You traded chaos for control, {name}.",
  "Budget brain activated—great job, {name}.",
  "Emergencies become inconveniences with habits like this, {name}.",
  "Adulting at its finest, {name}. Proud.",
  "Every penny is a vote for your goals, {name}.",
  "Consistency is your superpower, {name}.",
  "Small steps, massive change, {name}.",
  "Calm money, clear mind, {name}.",
  "Future you approves this move, {name}.",
  "Wealth likes boring—solid entry, {name}.",
  "Streaks make stories—good chapter, {name}.",
  "You're building options, {name}. Keep going.",
  "The plan is working, {name}.",
  "Every line tells progress, {name}.",
  "Impulse can wait—nice defense, {name}.",
  "Numbers before emotions—well played, {name}.",
  "Your goals just stepped closer, {name}.",
  "Smooth finances ahead, {name}.",
  "Less fog, more focus, {name}.",
  "Money listens when you lead, {name}.",
  "Compound confidence unlocked, {name}.",
  "Wealth is learned—keep stacking, {name}.",
  "Choosing values is choosing wealth, {name}.",
  "Freedom wall rising—another brick, {name}.",
  "Cash-flow clarity, chef's kiss, {name}.",
  "Budget armor: upgraded again, {name}.",
  "You showed up; results will too, {name}.",
  "Aligned spend = aligned life, {name}.",
  "Boundaries build freedom—solid stance, {name}.",
  "Plan over impulse—great call, {name}.",
  "Momentum unlocked—entry locked, {name}.",
  "The math loves neat, {name}. So do your goals.",
  "Aim true, {name}. Focus wins.",
  "You're trending up, {name}.",
  "No rush, just rise, {name}.",
  "You bought options today, {name}.",
  "Clarity credited, {name}.",
  "You honored the budget, {name}.",
  "Debt disliked that one, {name}.",
  "Savings smiled again, {name}.",
  "Nice guardrails, {name}.",
  "You led today; money followed, {name}.",
  "Nice save, {name}—impulse just cried a little.",
  "Pro-level patience, {name}.",
  "Keep the streak alive, {name}.",
  "You just banked peace, {name}.",
  "Masterful logging, {name}.",
  "Budget boss energy, {name}.",
  "Every line matters, {name}.",
  "Tiny hinge, big door, {name}.",
  "Future you is cheering, {name}.",
  "Bulletproof habit, {name}.",
  "Strong signal—goals ahead, {name}.",
  "Your budget breathed a sigh of relief, {name}.",
  "Quiet work, loud results—nice, {name}.",
  "Another mastery notch, {name}.",
  "Freedom can run now—tracking done, {name}.",
  "Purpose over impulse, {name}.",
  "You swept the path for wealth, {name}.",
  "Receipts in order, life in stride, {name}.",
  "Receipts: 1, excuses: 0, {name}.",
  "Repeat this and watch life change, {name}.",
  "You told the shiny thing 'not today,' {name}.",
  "Adulting win achieved in seconds, {name}.",
  "Attention is your richest asset, {name}.",
  "Savings seeds planted, {name}.",
  "Less guessing, more progressing, {name}.",
  "You're buying back your time, {name}.",
  "Another layer of safety built, {name}.",
  "Cents stacked; stress unstacked, {name}.",
  "You honored your priorities, {name}.",
  "Best budget is the one you use—like you just did, {name}.",
  "Control today creates options tomorrow, {name}.",
  "This is how dreams pay rent, {name}.",
  "From autopilot to intentional—nice, {name}.",
  "Your plan is louder than the purchase, {name}.",
  "Stability starts with steps like this, {name}.",
  "Cash-flow calm achieved, {name}.",
  "Lifestyle creep kept on a leash, {name}.",
  "Every clear log lowers friction, {name}.",
  "Budget aligned, energy refined, {name}.",
  "Driver's seat: you, {name}.",
  "Habits win—another proof, {name}.",
  "Swipe fatigue? Not on your watch, {name}.",
  "Savings snowball rolled forward, {name}.",
  "Future vacations will thank you, {name}.",
  "Twenty seconds for years of ease—done, {name}.",
  "You gave your goals a time slot, {name}.",
  "Clean numbers, confident choices, {name}.",
  "You made room for values, {name}.",
  "Your wallet exhaled—nice, {name}.",
  "Emergency fund sleeps better now, {name}.",
  "Less noise, more net worth, {name}.",
  "This version of you? Wealth's favorite, {name}.",
  "Peace of mind credited, {name}.",
  "Trajectory tilted upward, {name}.",
  "Breadcrumbs for better decisions—laid, {name}.",
  "Grown-up greatness in action, {name}.",
  "Your budget is a boundary with love, {name}.",
  "You watered the money plant, {name}.",
  "Freedom over friction—nice pick, {name}.",
  "Keep chiseling—the sculpture is you, {name}.",
  "You steered clear of chaos, {name}.",
  "Each track is a tiny tax on temptation, {name}.",
  "Routines rescue budgets—you're in one, {name}.",
  "Great restraint, great results, {name}.",
  "Quiet discipline, loud wealth, {name}.",
  "Net worth just got personality, {name}.",
  "You trimmed the financial weeds, {name}.",
  "Patience profit activated, {name}.",
  "Future choices made obvious, {name}.",
  "Your spreadsheet would high-five you, {name}.",
  "Goal tunnel is brighter, {name}.",
  "Data beats drama—nicely done, {name}.",
  "You built a moat around your money, {name}.",
  "You told your money where to go, {name}.",
  "Micro-investment in yourself—done, {name}.",
  "One line at a time, write the story, {name}.",
  "Your budget is becoming a habit home, {name}.",
  "You kept the promise you made to you, {name}.",
  "Vote for long-term joy cast, {name}.",
  "You nudged your wealth upward, {name}.",
  "Another rep for your financial muscles, {name}.",
  "From spend drift to spend shift, {name}.",
  "Compounding character in progress, {name}.",
  "Your habits are getting expensive—for your debt, {name}.",
  "Intentional beats impulsive—always, {name}.",
  "Line drawn and kept, {name}.",
  "Priorities showing—and they look good, {name}.",
  "You saved yourself future guesswork, {name}.",
  "You bought freedom, not clutter, {name}.",
  "Money likes a map; you made one, {name}.",
  "Budget a little more bulletproof now, {name}.",
  "Your goals were the loudest voice, {name}.",
  "You fed the plan, not the urge, {name}.",
  "Financial thermostat set to calm, {name}.",
  "You're building margin, not just money, {name}.",
  "Seriousness now looks like success, {name}.",
  "Information turned into intention—chef's kiss, {name}.",
  "Calm budget, bold life, {name}.",
  "You gave your future a tiny raise, {name}.",
  "Main thing stayed the main thing, {name}.",
  "This buys back mornings and nights, {name}.",
  "Boring wins are the best kind, {name}.",
  "Your money just got a manager—you, {name}.",
  "You're teaching your wallet patience, {name}.",
  "Yes to goals, no to noise—nice, {name}.",
  "You spent like a strategist today, {name}.",
  "You turned a purchase into a plan, {name}.",
  "You refused to let money go missing, {name}.",
  "Another proof you can be trusted with more, {name}.",
  "Wealth likes rhythm—keep rolling, {name}.",
  "You stayed on mission—smart step, {name}.",
  "Clutch tracking, {name}. Keep it up.",
  "Guesswork dodged—well played, {name}.",
  "Retail therapy can wait its turn, {name}.",
  "Budget 1, Shiny 0, {name}.",
  "You leveled up your calm, {name}.",
  "Financial focus locked in, {name}.",
  "You honored your plan today, {name}.",
  "Another quiet victory, {name}.",
  "You guided your cash on purpose, {name}.",
  "Your goals felt that one, {name}.",
  "Winner energy, {name}. Keep going.",
  "Banking better habits, {name}.",
  "Keep chiseling; results stack, {name}.",
  "Streak strong, {name}.",
  "You're building breathing room, {name}.",
  "Accountability looks good on you, {name}.",
  "From wish to plan to action—nice, {name}.",
  "You undercut the impulse, {name}.",
  "Elite patience on display, {name}.",
  "Big picture protected, {name}.",
  "You are trending wealthier, {name}.",
  "Trust the math and the habit, {name}.",
  "Your future weekends will thank you, {name}.",
  "Budget fluency unlocked, {name}.",
  "Earned confidence credited, {name}.",
  "Precision over perfection, {name}.",
  "Guardrails up and working, {name}.",
  "Solid rep—keep stacking, {name}.",
  "Deposit into discipline made, {name}.",
  "You practiced prosperity again, {name}.",
  "You made room for your goals, {name}.",
  "Excellent restraint, {name}. Proud.",
  "Clarity over clutter—chosen, {name}.",
  "Level-headed and level-upped, {name}.",
  "Budget ninja move—silent but powerful, {name}.",
  "Finance brain online; impulse on hold, {name}.",
  "You gave your money a map and a snack, {name}.",
  "Cash behaved today; you're the zookeeper, {name}.",
  "Receipt wrangled; chaos wrangled, {name}.",
  "Data in; wisdom out, {name}.",
  "ROI over FOMO—delicious choice, {name}.",
  "You speed-ran adulting in five seconds, {name}.",
  "Logged and loaded—keep steering, {name}.",
  "Decision made; goal paid, {name}.",
  "Plan honored; path cleared, {name}.",
  "Track, learn, adjust, repeat—relentless, {name}.",
  "Boom, {name}! Another log added to your highlight reel.",
  "Clean entry, {name}—your future self just fist-bumped the air.",
  "Cha-ching discipline unlocked, {name}. Keep farming wins.",
  "Budget boss online, {name}. Temptation went offline.",
  "Precision like a sniper, {name}. Expenses don't stand a chance.",
  "Another brick in your freedom fortress, {name}.",
  "Receipts bowed to your order, {name}.",
  "You pressed 'track' and chaos pressed 'quit,' {name}.",
  "Streak protected, {name}. Algorithms of wealth smiling.",
  "Numbers neat, nerves neat, {name}.",
  "You piloted the wallet like a pro, {name}—no turbulence.",
  "That’s a vote for calm cash flow, {name}.",
  "You just paid your goals in attention, {name}.",
  "Zero drama, full data—chef's kiss, {name}.",
  "Wallet whisperer mode: ON, {name}.",
  "You’re the CFO and the MVP today, {name}.",
  "Future vacations whispered: 'thanks, {name}'.",
  "Money map updated, {name}. Detours denied.",
  "Another quiet W on the board, {name}.",
  "Clarity rising, stress declining—trend approved, {name}.",
  "Budget armor reinforced, {name}. Proceed boldly.",
  "You turned impulse into insight, {name}.",
  "Solid rep, {name}. Gains are allergic to excuses.",
  "Your focus just outplayed your FOMO, {name}.",
  "You’re training money like a well-behaved dog, {name}.",
  "Receipts organized, chaos vaporized, {name}.",
  "Your spreadsheet is blushing, {name}.",
  "Progress so clean it squeaks, {name}.",
  "Another notch on the 'responsible adult' belt, {name}.",
  "You aimed at freedom and hit log, {name}.",
  "Calm wallet, loud future, {name}.",
  "Legendary patience spotted, {name}.",
  "You’re building options, not excuses, {name}.",
  "Congrats, {name}—you turned a swipe into strategy.",
  "That’s one more receipt that works for you, {name}.",
  "You just told your money who’s boss, {name}.",
  "Budget GPS recalculated—on route, {name}.",
  "Proud coach face activated for you, {name}.",
  "Another 'nope' to lifestyle creep, {name}.",
  "You kept the promise you made last paycheck, {name}.",
  "Tiny tap, giant trajectory, {name}.",
  "Audit-ready energy, {name}. Respect.",
  "The calm you want is built like this, {name}.",
  "You’re speedrunning maturity, {name}. PB achieved.",
  "That entry bench-pressed your debt, {name}.",
  "Focus so sharp it cut the impulse tag, {name}.",
  "You budgeted like it’s a boss fight—and won, {name}.",
  "Your habits are getting expensive for your bad decisions, {name}.",
  "Another day, another disciplined dollar, {name}.",
  "You kept the main thing the main thing, {name}.",
  "Wealth’s favorite sound is this log, {name}.",
  "Scroll less, save more—nailed it, {name}.",
  "You’re stacking boring wins—the elite kind, {name}.",
  "Clarity credits deposited, {name}.",
  "Big-picture brain engaged, {name}.",
  "Impulse shopping just rage-quit, {name}.",
  "You’re building a moat around your future, {name}.",
  "Receipts lined up like ducks—nice herding, {name}.",
  "Numbers don’t lie, and you don’t flinch, {name}.",
  "Your wealth engine just purred, {name}.",
  "Control looks great on you, {name}.",
  "You traded shiny for strategy, {name}.",
  "Another breadcrumb for better choices, {name}.",
  "Your money got a manager, and it’s you, {name}.",
  "This is the quiet flex, {name}.",
  "Budget fluency unlocked—speak rich, {name}.",
  "You installed another brick in Peace of Mind, {name}.",
  "That’s how you buy back hours, {name}.",
  "Goals fed, gremlins unfed, {name}.",
  "Savings bar moved—ding!—nice, {name}.",
  "Minimal effort, maximal signal—smart play, {name}.",
  "You turned a maybe into a metric, {name}.",
  "Wallet did a tiny happy dance, {name}.",
  "That click said 'I’m in charge,' {name}.",
  "Look at you, {name}, domestication of chaos specialist.",
  "Debt heard footsteps—yours, {name}.",
  "You picked compass over crowd, {name}.",
  "From wish to plan to action—smooth, {name}.",
  "Another day your future trusts you, {name}.",
  "You just raised your standard again, {name}.",
  "Your budget’s heartbeat is steady, {name}.",
  "You kept temptation in the penalty box, {name}.",
  "Big 'I got this' energy, {name}.",
  "Progress bar: +1% patience, {name}.",
  "You drafted your dollars like a coach, {name}.",
  "Balance looks better than impulse, {name}.",
  "This is the rep that others skip, {name}.",
  "Ruthless on habits, gentle on yourself—elite mix, {name}.",
  "You cut the fluff and fed the plan, {name}.",
  "Another micro-raise for Future {name}.",
  "Your inner CFO just did a mic drop, {name}.",
  "You said 'not today' to random, {name}.",
  "Precision beats vibes—you chose right, {name}.",
  "Your receipts are getting organized; be afraid, chaos—{name} is here.",
  "You’re writing a richer story one line at a time, {name}.",
  "Less retail therapy, more real therapy for your goals, {name}.",
  "Plan honored. Path cleared. Keep walking, {name}.",
  "Budget beast mode stays undefeated, {name}.",
  "Tiny hinge, giant door—swing it open, {name}.",
  "Your wallet just learned boundaries, {name}.",
  "Clutter declined; clarity accepted, {name}.",
  "You’re making compound interest jealous, {name}.",
  "Another receipt rescued from the wild, {name}.",
  "You’re the plot twist your debt didn’t expect, {name}.",
  "This is how myths of 'overnight success' are built, {name}.",
  "You logged like a scientist and a monk, {name}.",
  "Your attention is wealth’s favorite currency, {name}.",
  "That’s a financially attractive habit, {name}.",
  "You kept your budget breathable, {name}.",
  "Impulse tried to DM; you left it on read, {name}.",
  "Coach’s note: keep bullying stray expenses, {name}.",
  "Receipts tame, dragons lame—nice questing, {name}.",
  "Sleep better tonight—you earned it, {name}.",
  "You gave your future a tiny raise again, {name}.",
  "You’re farming freedom, one tap at a time, {name}.",
  "Budget shield up, {name}. Lasers deflected.",
  "You traded hype for habits—premium swap, {name}.",
  "Another line of code in your money OS, {name}.",
  "You made the next decision obvious, {name}.",
  "Stability fans are chanting your name—literally, {name}.",
  "You’re allergic to chaos and it shows, {name}.",
  "You just nerfed lifestyle creep, {name}.",
  "That’s a pro-level 'no thanks,' {name}.",
  "Receipts rallied; you led the team, {name}.",
  "You told your dollars their job—excellent management, {name}.",
  "That’s how you turn 'someday' into 'scheduled,' {name}.",
  "Microwave effort, slow-cooker results—patience chef, {name}.",
  "You clipped the wings of impulse, {name}.",
  "Respect, {name}—you audit-proofed your day.",
  "This log is your quiet swagger, {name}.",
  "Your discipline is louder than sales, {name}.",
  "You’re building a reputation with yourself, {name}.",
  "The boring stuff is buying the good stuff, {name}.",
  "Another receipt, another reason to relax, {name}.",
  "Congrats on the new boundary PR, {name}.",
  "Your goals texted me: 'We felt that,' {name}.",
  "You turned 'oops' potential into 'operational,' {name}.",
  "You’re compounding credibility, {name}.",
  "Impulse threw a tantrum. You sipped water, {name}.",
  "Budget zen achieved—namasté, {name}.",
  "You left the chaos group chat, {name}.",
  "Another clean pass in the money game, {name}.",
  "You’re the kind of consistent the market respects, {name}.",
  "Your budget spine is straight, {name}.",
  "You kept the wolves of waste outside, {name}.",
  "Receipts in, regrets out—solid trade, {name}.",
  "You stitched another thread of safety, {name}.",
  "You picked strategy over shiny again, {name}.",
  "That’s billionaire behavior at starter level, {name}.",
  "You muted the siren song of 'add to cart,' {name}.",
  "Budget rhythm smooth—DJ {name} on the decks.",
  "You’re cooking with clarity—no smoke, {name}.",
  "Your money is learning table manners, {name}.",
  "You put your impulse on airplane mode, {name}.",
  "That log has main-character energy, {name}.",
  "Receipts squared away; peace squared too, {name}.",
  "You’re wealth-lifting—form looks perfect, {name}.",
  "You bench-pressed a bad habit today, {name}.",
  "Another 'I do hard things' rep, {name}.",
  "You sealed a tiny leak, saved a future storm, {name}.",
  "Numbers aligned like constellations, {name}.",
  "You scripted another scene in 'Calm Finances,' {name}.",
  "Net worth loves your vibe, {name}.",
  "You made the budget your friend, not your warden, {name}.",
  "Your receipts salute their captain, {name}.",
  "You kept the gate; no goblins through, {name}.",
  "That’s the kind of click that moves mountains, {name}.",
  "Another inch forward beats a mile of excuses, {name}.",
  "You’re making your comfort zone earn its keep, {name}.",
  "You turned might spend into mindful spend, {name}.",
  "Your plan walked taller after that, {name}.",
  "You organized chaos like a librarian ninja, {name}.",
  "Savings smiled. Debt sulked. Classic, {name}.",
  "You’re the reason your future is less chaotic, {name}.",
  "You put respect on your paycheck, {name}.",
  "Clarity: installed. Drama: uninstalled, {name}.",
  "You traded 'why not?' for 'here’s why,' {name}.",
  "Another boring masterpiece, {name}.",
  "You denied the dopamine for the dividend, {name}.",
  "That’s a CEO decision, {name}.",
  "You practiced prosperity on purpose, {name}.",
  "Receipts behaved; you conducted them, {name}.",
  "You just made temptation fill out a form, {name}.",
  "Savings streak: protected, {name}.",
  "Budget beast fed and happy, {name}.",
  "You gave the future less to worry about, {name}.",
  "You kept cash classy, {name}.",
  "You dusted shelves in the money library, {name}.",
  "Another day, another 'no' that made room for better, {name}.",
  "You set the thermostat to 'calm wealth,' {name}.",
  "Receipts organized like a parade—march on, {name}.",
  "You built trust with yourself again, {name}.",
  "That’s a tiny hinge with a VIP pass, {name}.",
  "You’re editing your money story like an author, {name}.",
  "You told your dollars to sit—and they did, {name}.",
  "You made your budget breathable, {name}.",
  "Signals strong; mission on course, {name}.",
  "Quietly elite behavior, {name}.",
  "You invested ten seconds and dodged ten headaches, {name}.",
  "Your budget swagger just leveled up, {name}.",
  "That click said discipline over drama, {name}.",
  "You put your goals on speakerphone, {name}.",
  "Receipts squared, mindset squared, {name}.",
  "You chose 'later win' over 'now wow,' {name}.",
  "Your future thanked your present—for real, {name}.",
  "You stopped a leak before it learned to swim, {name}.",
  "That’s how you steal power back from impulse, {name}.",
  "You kept your lane and gained ground, {name}.",
  "Budget math > sales math—nice choice, {name}.",
  "You tuned your finances like an instrument, {name}.",
  "Another entry, another exhale, {name}.",
  "You made space for better decisions, {name}.",
  "Financial gravity pulled toward your goals, {name}.",
  "You made 'one day' jealous, {name}.",
  "Receipts: tamed. Gremlins: blamed. Good work, {name}.",
  "You cut noise like a laser, {name}.",
  "That log was a love letter to Future {name}.",
  "You taught your money posture, {name}.",
  "You iced the impulse, warmed the wisdom, {name}.",
  "Plan executed with main-character poise, {name}.",
  "You took the wheel back from autopilot, {name}.",
  "Savings got a tiny six-pack—nice reps, {name}.",
  "You gave chaos a curfew, {name}.",
  "That’s a grown move, {name}.",
  "You held the line like a legend, {name}.",
  "Receipts in formation—General {name} reporting.",
  "You spent like a strategist, not a scroll zombie, {name}.",
  "You locked in, and life unlocks later, {name}.",
  "You just made 'afford it' less about luck, {name}.",
  "Your plan survived another temptation meteor, {name}.",
  "You kept the budget breathable and brave, {name}.",
  "Audit angels sang your name—{name}. Beautiful.",
  "You aimed for steady and hit excellent, {name}.",
  "That log was a tiny standing ovation, {name}.",
  "You put your values on the calendar, {name}.",
  "Receipts behaving like well-trained cats—rare, {name}.",
  "You ran the play, not the excuse, {name}.",
  "Bull market in your self-respect, {name}.",
  "You filed the chaos under 'not today,' {name}.",
  "You kept your budget spicy and your spending mild, {name}.",
  "That was an adulting masterclass, {name}.",
  "You rehearsed prosperity again, {name}.",
  "You made your wallet proud—not loud, {name}.",
  "You held your ground at checkout, {name}.",
  "Receipts synced; worries unsynced, {name}.",
  "You moved like a person who gets rich slowly, {name}.",
  "Your discipline has fan art now, {name}.",
  "You told 'add to cart' to take a seat, {name}.",
  "You set a trap and caught a bad habit, {name}.",
  "Your savings just winked, {name}.",
  "You kept your dopamine honest, {name}.",
  "Receipts in rows, confidence in columns, {name}.",
  "You took a step only legends repeat, {name}.",
  "You made your goals easier to reach than excuses, {name}.",
  "That was a classy rejection of chaos, {name}.",
  "You upgraded from intention to instruction, {name}.",
  "Your budget has standards—and you met them, {name}.",
  "You parked the impulse and fueled the plan, {name}.",
  "Financial feng shui achieved, {name}.",
  "You pressed pause on the 'treat yourself' saga, {name}.",
  "Receipts tidy, horizon wider, {name}.",
  "You coached your wallet mid-game, {name}.",
  "Another vote for freedom, cast by {name}.",
  "You turned a temptation cliff into a curb, {name}.",
  "Your money learned the word 'respect,' {name}.",
  "You paid attention—the rarest currency, {name}.",
  "Receipts lined up like soldiers; march on, {name}.",
  "You shifted from spending to steering, {name}.",
  "Savings playlist on repeat, {name}.",
  "You kept your budget hydrated and healthy, {name}.",
  "That’s the patience that buys plane tickets, {name}.",
  "You made the hard thing look casual, {name}.",
  "Your self-control just posted a PR, {name}.",
  "Receipts filed, villain foiled, {name}.",
  "You transformed 'oops' into 'on it,' {name}.",
  "You put a seatbelt on your spending, {name}.",
  "This is the vibe that retires early, {name}.",
  "You kept your narrative in the driver's seat, {name}.",
  "Receipts balanced; swagger balanced too, {name}.",
  "You sent debt a polite breakup text, {name}.",
  "That was a pH balance for your finances, {name}.",
  "You tightened the bolts on your budget, {name}.",
  "Savings gained XP; you leveled up, {name}.",
  "Another micro-win, macro-impact moment, {name}.",
  "You chose the boring miracle, {name}.",
  "Receipts under control; dreams under construction, {name}.",
  "You kept the wolves outside the spreadsheet, {name}.",
  "That’s a money-moves montage moment, {name}.",
  "You stayed dangerous—to your bad habits, {name}.",
  "Receipts clean, conscience cleaner, {name}.",
  "You made your budget a safe habitat, {name}.",
  "You added one more yes to future freedom, {name}.",
  "You left chaos on read again, {name}.",
  "Savings looked you dead in the eye and smiled, {name}.",
  "You pushed the needle without pushing panic, {name}.",
  "Your wallet prefers this version of you, {name}.",
  "Receipts said 'sir/ma’am, yes sir/ma’am' to {name}.",
  "You did the unsexy thing—and that’s why it works, {name}.",
];

/**
 * Get a random motivational quote with user's name
 */
export function getRandomQuote(userName: string): string {
  const randomIndex = Math.floor(Math.random() * MOTIVATIONAL_QUOTES.length);
  const quote = MOTIVATIONAL_QUOTES[randomIndex];
  return quote.replace(/{name}/g, userName);
}

/**
 * Format spending confirmation message
 * Returns message with quote in italic (Telegram markdown format)
 */
export function formatSpendingConfirmation(
  amount: number,
  currency: string,
  spendingName: string,
  userName: string
): string {
  const transactionLine = `${amount} ${currency} - ${spendingName}`;
  const quote = getRandomQuote(userName);
  // Escape markdown special characters in quote to prevent formatting issues
  // Escape underscores (used for italic), asterisks, brackets, etc.
  const escapedQuote = quote
    .replace(/_/g, '\\_')      // Escape underscores
    .replace(/\*/g, '\\*')     // Escape asterisks
    .replace(/\[/g, '\\[')      // Escape opening brackets
    .replace(/\]/g, '\\]')     // Escape closing brackets
    .replace(/\(/g, '\\(')     // Escape opening parentheses
    .replace(/\)/g, '\\)');    // Escape closing parentheses
  // Make quote italic using Telegram markdown
  const italicQuote = `_${escapedQuote}_`;
  return `${transactionLine}\n\n${italicQuote}`;
}

/**
 * Format earning confirmation message
 * Returns message with quote in italic (Telegram markdown format)
 */
export function formatEarningConfirmation(
  amount: number,
  currency: string,
  earningName: string,
  userName: string
): string {
  const transactionLine = `+${amount} ${currency} - ${earningName}`;
  const quote = getRandomQuote(userName);
  // Escape markdown special characters in quote to prevent formatting issues
  // Escape underscores (used for italic), asterisks, brackets, etc.
  const escapedQuote = quote
    .replace(/_/g, '\\_')      // Escape underscores
    .replace(/\*/g, '\\*')     // Escape asterisks
    .replace(/\[/g, '\\[')      // Escape opening brackets
    .replace(/\]/g, '\\]')     // Escape closing brackets
    .replace(/\(/g, '\\(')     // Escape opening parentheses
    .replace(/\)/g, '\\)');    // Escape closing parentheses
  // Make quote italic using Telegram markdown
  const italicQuote = `_${escapedQuote}_`;
  return `${transactionLine}\n\n${italicQuote}`;
}

