/**
 * Motivational quotes for spending confirmations
 * Format: quotes contain {name} placeholder that will be replaced with user's name
 */

export const MOTIVATIONAL_QUOTES = [
  "Nice move, {name}. Every penny has a purpose.",
  "Great tracking, {name}—clarity today, freedom tomorrow.",
  "Well done, {name}. Consistency compounds.",
  "Another clean log, {name}. Momentum loves this.",
  "Strong choice, {name}—future you says thanks.",
  "Every entry is a deposit into discipline, {name}.",
  "Budget updated, {name}; stress downgraded.",
  "You just voted for your goals with your wallet, {name}.",
  "Tiny action, big trajectory, {name}.",
  "Your plan > your impulses, {name}. Keep going.",
  "Recorded and remembered, {name}—money obeys math.",
  "Precision today, peace later, {name}.",
  "Progress over perfection, {name}. Keep stacking.",
  "Stacking wins like coins, {name}.",
  "Tracking is training, {name}. You're getting stronger.",
  "Legendary consistency, {name}—keep cashing it in.",
  "Another brick in your freedom wall, {name}.",
  "Smarter chapter added to your money story, {name}.",
  "Logs like this turn dreams into line items, {name}.",
  "That click is the sound of control, {name}.",
  "You guided money; it didn't guide you, {name}.",
  "Discipline looks good on you, {name}.",
  "Habits like this build safety nets, {name}.",
  "Order made, chaos avoided—well played, {name}.",
  "Budget boundaries protect your joy, {name}.",
  "Microwin achieved, {name}. Macro gains incoming.",
  "Accuracy today makes choices easy tomorrow, {name}.",
  "Future you is high-fiving you, {name}.",
  "Wealth sneaks up on habits like yours, {name}.",
  "You paid your goals first—with attention, {name}.",
  "Calm cash beats loud purchases, {name}.",
  "Streak protected, {name}. Nice work.",
  "Notebook brain, investor heart, {name}—love it.",
  "From wishful to mindful in one tap, {name}.",
  "The trend line smiled at you, {name}.",
  "Entry locked, temptations blocked, {name}.",
  "Slow is smooth, smooth is rich, {name}.",
  "Values over vibes—chef's kiss, {name}.",
  "Boss move: budget first, then life, {name}.",
  "Receipts of progress filed, {name}.",
  "You're training your money to behave, {name}.",
  "Control earned, {name}. Feels good, right?",
  "Your goals are in range, {name}. Signals clear.",
  "That was a vote for financial freedom, {name}.",
  "Numbers noted, nervousness muted, {name}.",
  "You're building options, not just savings, {name}.",
  "Money clarity activated, {name}.",
  "Another notch on your wealth belt, {name}.",
  "Quiet win, loud future, {name}.",
  "Tiny hinges swing big doors, {name}.",
  "Compound returns love consistent trackers like you, {name}.",
  "Every line item is leadership, {name}.",
  "Budget armor upgraded, {name}.",
  "Cents into sense—nice work, {name}.",
  "Road to rich is paved with logs like this, {name}.",
  "You're buying time, not things, {name}.",
  "Minutes of tracking; years of payoff, {name}.",
  "From chaos to cadence—clean entry, {name}.",
  "{name}, you're the CFO of your life.",
  "Budget beast mode engaged, {name}.",
  "Debt hated what you just did, {name}.",
  "Savings smiled; impulse pouted, {name}.",
  "You made temptation wait its turn, {name}.",
  "Habit over hype—great form, {name}.",
  "Aligned spend, aligned life, {name}.",
  "Good call—needs over noise, {name}.",
  "You kept tomorrow's promise, {name}.",
  "The plan got sharper, and so did you, {name}.",
  "Beginner mode now; pro soon, {name}.",
  "Clean entry, clear conscience, {name}.",
  "Your goals just got closer, {name}.",
  "Strong log, less fog, {name}.",
  "Your baseline is rising, {name}. Keep going.",
  "Make money boring; make life exciting, {name}.",
  "Order in the budget, peace in the mind, {name}.",
  "Your priorities are showing—in a good way, {name}.",
  "Money knows who's boss: you, {name}.",
  "Win logged; confidence credited, {name}.",
  "You protected your peace and your purse, {name}.",
  "Calm, clear, consistent—wealth loves that, {name}.",
  "Receipts don't lie; streaks don't either, {name}.",
  "Budget updated; motivation upgraded, {name}.",
  "Steady hands, steady plans, {name}.",
  "Wealth is a habit—keep repping, {name}.",
  "Progress over impulse—textbook, {name}.",
  "Tracking today keeps regret away, {name}.",
  "Future decisions just got easier, {name}.",
  "That entry punched debt in the face, {name}.",
  "Savings meter ticked up, {name}.",
  "Mastering money, not chasing it—nice, {name}.",
  "Another disciplined dollar, {name}.",
  "Goals fed; impulse unfed, {name}.",
  "Your path is visible, {name}. Crystal clear.",
  "You keep your budget promises, {name}.",
  "Long game pro move, {name}.",
  "Guardrails held—well done, {name}.",
  "Financial muscles engaged, {name}.",
  "Clarity is compounding, {name}.",
  "You banked a little more freedom, {name}.",
  "Logs like this build legacies, {name}.",
  "You traded chaos for control, {name}.",
  "Budget brain activated—great job, {name}.",
  "Emergencies become inconveniences with habits like this, {name}.",
  "Adulting at its finest, {name}. Proud.",
  "Every penny is a vote for your goals, {name}.",
  "Consistency is your superpower, {name}.",
  "Small steps, massive change, {name}.",
  "Calm money, clear mind, {name}.",
  "Future you approves this move, {name}.",
  "Wealth likes boring—solid entry, {name}.",
  "Streaks make stories—good chapter, {name}.",
  "You're building options, {name}. Keep going.",
  "The plan is working, {name}.",
  "Every line tells progress, {name}.",
  "Impulse can wait—nice defense, {name}.",
  "Numbers before emotions—well played, {name}.",
  "Your goals just stepped closer, {name}.",
  "Smooth finances ahead, {name}.",
  "Less fog, more focus, {name}.",
  "Money listens when you lead, {name}.",
  "Compound confidence unlocked, {name}.",
  "Wealth is learned—keep stacking, {name}.",
  "Choosing values is choosing wealth, {name}.",
  "Freedom wall rising—another brick, {name}.",
  "Cash-flow clarity, chef's kiss, {name}.",
  "Budget armor: upgraded again, {name}.",
  "You showed up; results will too, {name}.",
  "Aligned spend = aligned life, {name}.",
  "Boundaries build freedom—solid stance, {name}.",
  "Plan over impulse—great call, {name}.",
  "Momentum unlocked—entry locked, {name}.",
  "The math loves neat, {name}. So do your goals.",
  "Aim true, {name}. Focus wins.",
  "You're trending up, {name}.",
  "No rush, just rise, {name}.",
  "You bought options today, {name}.",
  "Clarity credited, {name}.",
  "You honored the budget, {name}.",
  "Debt disliked that one, {name}.",
  "Savings smiled again, {name}.",
  "Nice guardrails, {name}.",
  "You led today; money followed, {name}.",
  "Nice save, {name}—impulse just cried a little.",
  "Pro-level patience, {name}.",
  "Keep the streak alive, {name}.",
  "You just banked peace, {name}.",
  "Masterful logging, {name}.",
  "Budget boss energy, {name}.",
  "Every line matters, {name}.",
  "Tiny hinge, big door, {name}.",
  "Future you is cheering, {name}.",
  "Bulletproof habit, {name}.",
  "Strong signal—goals ahead, {name}.",
  "Your budget breathed a sigh of relief, {name}.",
  "Quiet work, loud results—nice, {name}.",
  "Another mastery notch, {name}.",
  "Freedom can run now—tracking done, {name}.",
  "Purpose over impulse, {name}.",
  "You swept the path for wealth, {name}.",
  "Receipts in order, life in stride, {name}.",
  "Receipts: 1, excuses: 0, {name}.",
  "Repeat this and watch life change, {name}.",
  "You told the shiny thing 'not today,' {name}.",
  "Adulting win achieved in seconds, {name}.",
  "Attention is your richest asset, {name}.",
  "Savings seeds planted, {name}.",
  "Less guessing, more progressing, {name}.",
  "You're buying back your time, {name}.",
  "Another layer of safety built, {name}.",
  "Cents stacked; stress unstacked, {name}.",
  "You honored your priorities, {name}.",
  "Best budget is the one you use—like you just did, {name}.",
  "Control today creates options tomorrow, {name}.",
  "This is how dreams pay rent, {name}.",
  "From autopilot to intentional—nice, {name}.",
  "Your plan is louder than the purchase, {name}.",
  "Stability starts with steps like this, {name}.",
  "Cash-flow calm achieved, {name}.",
  "Lifestyle creep kept on a leash, {name}.",
  "Every clear log lowers friction, {name}.",
  "Budget aligned, energy refined, {name}.",
  "Driver's seat: you, {name}.",
  "Habits win—another proof, {name}.",
  "Swipe fatigue? Not on your watch, {name}.",
  "Savings snowball rolled forward, {name}.",
  "Future vacations will thank you, {name}.",
  "Twenty seconds for years of ease—done, {name}.",
  "You gave your goals a time slot, {name}.",
  "Clean numbers, confident choices, {name}.",
  "You made room for values, {name}.",
  "Your wallet exhaled—nice, {name}.",
  "Emergency fund sleeps better now, {name}.",
  "Less noise, more net worth, {name}.",
  "This version of you? Wealth's favorite, {name}.",
  "Peace of mind credited, {name}.",
  "Trajectory tilted upward, {name}.",
  "Breadcrumbs for better decisions—laid, {name}.",
  "Grown-up greatness in action, {name}.",
  "Your budget is a boundary with love, {name}.",
  "You watered the money plant, {name}.",
  "Freedom over friction—nice pick, {name}.",
  "Keep chiseling—the sculpture is you, {name}.",
  "You steered clear of chaos, {name}.",
  "Each track is a tiny tax on temptation, {name}.",
  "Routines rescue budgets—you're in one, {name}.",
  "Great restraint, great results, {name}.",
  "Quiet discipline, loud wealth, {name}.",
  "Net worth just got personality, {name}.",
  "You trimmed the financial weeds, {name}.",
  "Patience profit activated, {name}.",
  "Future choices made obvious, {name}.",
  "Your spreadsheet would high-five you, {name}.",
  "Goal tunnel is brighter, {name}.",
  "Data beats drama—nicely done, {name}.",
  "You built a moat around your money, {name}.",
  "You told your money where to go, {name}.",
  "Micro-investment in yourself—done, {name}.",
  "One line at a time, write the story, {name}.",
  "Your budget is becoming a habit home, {name}.",
  "You kept the promise you made to you, {name}.",
  "Vote for long-term joy cast, {name}.",
  "You nudged your wealth upward, {name}.",
  "Another rep for your financial muscles, {name}.",
  "From spend drift to spend shift, {name}.",
  "Compounding character in progress, {name}.",
  "Your habits are getting expensive—for your debt, {name}.",
  "Intentional beats impulsive—always, {name}.",
  "Line drawn and kept, {name}.",
  "Priorities showing—and they look good, {name}.",
  "You saved yourself future guesswork, {name}.",
  "You bought freedom, not clutter, {name}.",
  "Money likes a map; you made one, {name}.",
  "Budget a little more bulletproof now, {name}.",
  "Your goals were the loudest voice, {name}.",
  "You fed the plan, not the urge, {name}.",
  "Financial thermostat set to calm, {name}.",
  "You're building margin, not just money, {name}.",
  "Seriousness now looks like success, {name}.",
  "Information turned into intention—chef's kiss, {name}.",
  "Calm budget, bold life, {name}.",
  "You gave your future a tiny raise, {name}.",
  "Main thing stayed the main thing, {name}.",
  "This buys back mornings and nights, {name}.",
  "Boring wins are the best kind, {name}.",
  "Your money just got a manager—you, {name}.",
  "You're teaching your wallet patience, {name}.",
  "Yes to goals, no to noise—nice, {name}.",
  "You spent like a strategist today, {name}.",
  "You turned a purchase into a plan, {name}.",
  "You refused to let money go missing, {name}.",
  "Another proof you can be trusted with more, {name}.",
  "Wealth likes rhythm—keep rolling, {name}.",
  "You stayed on mission—smart step, {name}.",
  "Clutch tracking, {name}. Keep it up.",
  "Guesswork dodged—well played, {name}.",
  "Retail therapy can wait its turn, {name}.",
  "Budget 1, Shiny 0, {name}.",
  "You leveled up your calm, {name}.",
  "Financial focus locked in, {name}.",
  "You honored your plan today, {name}.",
  "Another quiet victory, {name}.",
  "You guided your cash on purpose, {name}.",
  "Your goals felt that one, {name}.",
  "Winner energy, {name}. Keep going.",
  "Banking better habits, {name}.",
  "Keep chiseling; results stack, {name}.",
  "Streak strong, {name}.",
  "You're building breathing room, {name}.",
  "Accountability looks good on you, {name}.",
  "From wish to plan to action—nice, {name}.",
  "You undercut the impulse, {name}.",
  "Elite patience on display, {name}.",
  "Big picture protected, {name}.",
  "You are trending wealthier, {name}.",
  "Trust the math and the habit, {name}.",
  "Your future weekends will thank you, {name}.",
  "Budget fluency unlocked, {name}.",
  "Earned confidence credited, {name}.",
  "Precision over perfection, {name}.",
  "Guardrails up and working, {name}.",
  "Solid rep—keep stacking, {name}.",
  "Deposit into discipline made, {name}.",
  "You practiced prosperity again, {name}.",
  "You made room for your goals, {name}.",
  "Excellent restraint, {name}. Proud.",
  "Clarity over clutter—chosen, {name}.",
  "Level-headed and level-upped, {name}.",
  "Budget ninja move—silent but powerful, {name}.",
  "Finance brain online; impulse on hold, {name}.",
  "You gave your money a map and a snack, {name}.",
  "Cash behaved today; you're the zookeeper, {name}.",
  "Receipt wrangled; chaos wrangled, {name}.",
  "Data in; wisdom out, {name}.",
  "ROI over FOMO—delicious choice, {name}.",
  "You speed-ran adulting in five seconds, {name}.",
  "Logged and loaded—keep steering, {name}.",
  "Decision made; goal paid, {name}.",
  "Plan honored; path cleared, {name}.",
  "Track, learn, adjust, repeat—relentless, {name}.",
];

/**
 * Get a random motivational quote with user's name
 */
export function getRandomQuote(userName: string): string {
  const randomIndex = Math.floor(Math.random() * MOTIVATIONAL_QUOTES.length);
  const quote = MOTIVATIONAL_QUOTES[randomIndex];
  return quote.replace(/{name}/g, userName);
}

/**
 * Format spending confirmation message
 * Returns message with quote in italic (Telegram markdown format)
 */
export function formatSpendingConfirmation(
  amount: number,
  currency: string,
  spendingName: string,
  userName: string
): string {
  const transactionLine = `${amount} ${currency} - ${spendingName}`;
  const quote = getRandomQuote(userName);
  // Escape markdown special characters in quote to prevent formatting issues
  // Escape underscores (used for italic), asterisks, brackets, etc.
  const escapedQuote = quote
    .replace(/_/g, '\\_')      // Escape underscores
    .replace(/\*/g, '\\*')     // Escape asterisks
    .replace(/\[/g, '\\[')      // Escape opening brackets
    .replace(/\]/g, '\\]')     // Escape closing brackets
    .replace(/\(/g, '\\(')     // Escape opening parentheses
    .replace(/\)/g, '\\)');    // Escape closing parentheses
  // Make quote italic using Telegram markdown
  const italicQuote = `_${escapedQuote}_`;
  return `${transactionLine}\n\n${italicQuote}`;
}

